### PR TITLE
Added ServerPool and DSNInterface.

### PR DESCRIPTION
**Pull request by mj4444ru**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ✔️
| Fixed issues  |

### CODE REVIEW

**Comment by SamMousa** [comment]
@mj4444ru, could you add some docs to the interfaces? It is unclear what the purpose of getClass is, for example.

**Comment by mj4444ru** [comment]
> @mj4444ru, could you add some docs to the interfaces? It is unclear what the purpose of getClass is, for example.

These are very rough sketches for further discussion. I will briefly describe in the next comment.

**Comment by mj4444ru** [comment]
DSNInterface is an interface for DSN. But DSN is Data Source Name. In our case, we need rather Data Source Config - that is, DSC, which will contain, in addition to DSN, other server settings.

This DSC should tell us the class or other identifier for the factory that will instantiate the connection for us.

**Comment by terabytesoftw** [comment]
closed due to inactivity

**Pull request closed without merging**
