### PR TITLE
Remove unnecessary methods.

### PR DESCRIPTION
**Pull request by terabytesoftw**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌

### CODE REVIEW

**Review by samdark — APPROVED** [review]

**Review by darkdef — COMMENTED** [review]
How about case 

```php
 $query = (new Query())->
...
many rows for build query
...
->join('t1')->join('t2');

$result = $query->all();
$cnt = $query->setJoin([])->count();
```

I'm not agree with this changes

**Comment by cebe** [comment]
@darkdef that could be a use case, but in case you have Params added via join, the `setJoin` call will not remove them and the query will not work because more params are bound than are used in the query.

**Comment by darkdef** [comment]
> @darkdef that could be a use case, but in case you have Params added via join, the `setJoin` call will not remove them and the query will not work because more params are bound than are used in the query.

More syntetical examples:
$query->join('LEFT', 't1', 't1.id=t2.id')
join can be without parameters

**Comment by samdark** [comment]
OK. So we aren't removing methods.

**Pull request closed without merging**
