### PR TITLE
Fix DatabaseFactory constructor

### PR DESCRIPTION
**Pull request by rustamwin**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️/❌
| New feature?  | ❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | -

### CODE REVIEW

**Comment by terabytesoftw** [comment]
The tests fail we have to review.

**Comment by rustamwin** [comment]
> The tests fail we have to review, remove private function __construct(), it is not used in any part of the code.

It looks like failing tests not related this PR, private constructor prohibits instantiation.

**Comment by terabytesoftw** [comment]
> > The tests fail we have to review, remove private function __construct(), it is not used in any part of the code.
> 
> It looks like failing tests not related this PR, private constructor prohibits instantiation.

When the di container is defined and manufactures it, I will fix it while it can change more.

**Comment by terabytesoftw** [comment]
close in favor https://github.com/yiisoft/db/pull/240

**Pull request closed without merging**
